title: Misinformation Grinder
email: security@misinformationgrinder.tk
description: This site wants to report misinformation
baseurl: "docs/" 
twitter_username: trippingunicornlsd
github_username:  trippingunicornlsd
domain: misinformationgrinder.tk
url: https://misinformationgrinder.tk/
show_downloads: true

# Build settings
theme: jekyll-theme-leap-day
plugins:
  - jekyll-feed

# Google Analytics
google_analytics: G-M0N1D440KP
