title: Info Agents
email: security@info-agents.ml
description: This site wants to report misinformation
twitter_username: trippingunicornlsd
github_username:  trippingunicornlsd
domain: info-agents.ml
url: https://info-agents.ml/
show_downloads: true

# Build settings
theme: jekyll-theme-leap-day
plugins:
  - jekyll-feed

# Google Analytics
google_analytics: G-M0N1D440KP
